layout_spectrum: 0.5665013692341745
typography_spectrum: 0.008978418540209532
color:
  brandStrength: 0.9240420346613973
  lightness: 0.4751837288495153
  saturation: 0.640544704394415
  rhythmicContrast: 0.9487783424556255
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Hispanic Comics
